Repository googleapis/nodejs-proto-files, pull requests merged in 2020-07, with the labels that each got.

#299 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#302 fix: TypeScript error in got package
  package.json
Labels: cla: yes

#304 fix: make load handle imports properly
  src/load.ts
  test/load.test.ts
Labels: cla: yes

#309 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#307 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, gitattribute.*, in

#314 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#312 chore: adds back node 8 configuration (we can remove it again after)
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: cla: yes, context: none
